# This CloudBuild will be triggered by push to main branch
#

substitutions:
  _PROJECT_ID: elivery-app-388907
  _FUNCTION_NAME: delivery-app
  _REGION: europe-west2

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_FUNCTION_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_FUNCTION_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', '$_FUNCTION_NAME', '--image', 'gcr.io/$PROJECT_ID/$_FUNCTION_NAME', '--region', '$REGION', '--trigger-http']